gems:
- rspec =1.3.1 # circumvent JRUBY-5581 on rspec-1.3.2. Only necessary until update to JRuby 1.6.2+.
- buildr =1.4.4
- buildr-iidea =0.0.4
- buildr-bnd =0.0.6
- ivy4r =0.12.6
ivy:
  settings.file: ivy/ivysettings.xml
ant: 1.8.0
