package gov.nih.nci.cabig.ctms.grid.ae.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.4
 */
public interface AdverseEventConsumerConstantsBase {
	public static final String SERVICE_NS = "http://ae.grid.ctms.cabig.nci.nih.gov/AdverseEventConsumer";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "AdverseEventConsumerKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "AdverseEventConsumerResourceProperties");
	
}
