package gov.nih.nci.ccts.grid.smoketest.service.globus;

import gov.nih.nci.ccts.grid.smoketest.service.SmokeTestServiceImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the SmokeTestServiceImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public class SmokeTestServiceProviderImpl{
	
	SmokeTestServiceImpl impl;
	
	public SmokeTestServiceProviderImpl() throws RemoteException {
		impl = new SmokeTestServiceImpl();
	}
	

    public gov.nih.nci.ccts.grid.smoketest.stubs.PingResponse ping(gov.nih.nci.ccts.grid.smoketest.stubs.PingRequest params) throws RemoteException {
    gov.nih.nci.ccts.grid.smoketest.stubs.PingResponse boxedResult = new gov.nih.nci.ccts.grid.smoketest.stubs.PingResponse();
    impl.ping();
    return boxedResult;
  }

}
